### ISSUE TITLE
@N vs @S for pilot updates

### ISSUE THREAD

**Issue by norrisng** [norrisng/fsd-doc#4]
What's the distinction between `@N`/`@S` for pilot position updates? Both are used for both outgoing/incoming updates.

**Comment by aleccai8** [comment]
> `@N`/ `@S`飞行员位置更新之间的区别是什么？两者都用于传出/传入更新。

That means the modec and the mode s of the transponder

**Comment by norrisng** [comment]
Ahh, thanks! Looks like `@N` is Mode C, and `@S` is standby?

If you want, you can create a pull request, which would give you credit for it on GitHub :)

**Comment by norrisng** [comment]
@zhengheng7913 if you don't open a pull request by the end of the week, I'll update the relevant section. Will definitely mention your username in the commit message though, if that's what I end up doing.

**Comment by norrisng** [comment]
Included in fb796270bb05c8336cb618d93987d6dfb6662926.
